### ISSUE TITLE
Fix failing test cases

### ISSUE THREAD

**Issue by DigneshGujarathi** [glific/cypress-testing#108]
- [x] Chats -
Send attachment - Video
should go to top
should load more chats
should check help document

- [x] ChatCollection -
should send attachment to collection - Document

- [x] Chats -
should check unread messages
Select searched contact
Advanced search with name/tag/keyword
Advanced search with Includes tags

- [x] Collection - 
should add member to collection
should remove member from collection

- [x] ContactBar -
should view contact profile
should start a flow

- [ ] Flow -
should check require field validation
should create new Flow with keyword
should display flow keyword below the flow name
should edit Flow
should create duplicate Flow
should delete Flow

- [x] Message -
should tag a message
should remove tag from a message

- [x] Role - staff- chat -
should have only chat menu

- [x] Role - staff - chat -
Select searched contact
Advanced search with name/tag/keyword
Advanced search with Includes tags

- [x] Role - staff - Contactbar -
should view contact profile
should start a flow

- [x] Role - staff - Message -
should tag a message

- [x] Role - staff - Profile -
should load profile page and save successfully

- [x] Role - Staff - Blocked Contact -
should load blocked contacts list

- [x] Organization Settings-
should have valid available data

- [x] Organization Settings-
should check Gupshup settings
should check BigQuery settings
should check Google Cloud Storage settings

- [x] Profile-
should load profile page and save successfully

- [x] Staff management -
should create new collection
should assign collection to staff
should remove collection from staff
should save edit screen
should delete collection

- [x] Tag - 
should create new tag
should redirect to tag list
should edit tag
should delete tag

**Comment by mdshamoon** [comment]
Closing since this seems to be fixed
